services:
  imdb_ingest:
    build:
      context: ./askcinephile/imdb_ingest/
    container_name: askcinephile_imdb_ingest
    env_file: ./imdb_ingest/.env

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: askcinephile
    volumes:
      - ./askcinephile/database/db_volume:/var/lib/mysql
      - ./askcinephile/database/mysql-conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3306:3306"
    restart: unless-stopped
volumes:
  data:
