services:
  askcinephileDB:
    container_name: askcinephileDB
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: askcinephile
    volumes:
      - ./db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
volumes:
  data:
